---
title: "Taller 3"
subtitle: "Diseño Experimental"
author: "Edimer David Jaramillo"
date: "`r Sys.Date()`"
lang: es 
execute: 
  eval: true
  echo: true
  warning: false
format:
  html:
    page-layout: article
    fig-width: 6
    fig-height: 4.5
    toc: true
    toc-title: "Tabla de contenido"
    smooth-scroll: true
    code-fold: true
    df-print: paged
    toc-location: left
    number-depth: 4
    theme: yeti
    code-copy: true
    highlight-style: github
    code-tools:
      source: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center",
                      fig.width = 5.5, fig.height = 4.5, warning = FALSE,
                      message = FALSE)
```

# Descripción

  1. Instalar alguna de las aplicaciones: [Arduino Science Journal](https://www.arduino.cc/education/science-journal) o [PyPhox](https://phyphox.org/)
  2. Realizar mediciones de intensidad sonora (decibeles) en la biblioteca de la universidad. Las mediciones deberán ser realizadas en al menos 5 días.
  3. Construya un resumen descriptivo con los resultados de las mediciones.
  4. Construya un gráfico que permita comparar la distribución de la intensidad sonora en los días que realizó las mediciones.
  5. La [Organización Mundial de la Salud - OMS](https://www.who.int/es/news-room/questions-and-answers/item/deafness-and-hearing-loss-safe-listening) sugiere que el nivel de ruido permitido en las bibliotecas es 40 dB, su tarea es validar la siguiente hipótesis:

$$H_0: \mu = 40$$
$$H_1: \mu \neq 40$$

  6. Valide el supuesto de normalidad en sus datos.
  7. Determine si es adecuado utilizar métodos paramétricos o no paramétricos para contrastar la hipótesis y proporcionar un intervalo de confianza.
  8. Concluya con un nivel de significancia del 5%.

# Fecha máxima de entrega

- **Fecha de entrega máxima:** viernes 26 de abril de 2024.