---
title: "Ejemplos de inferencia con R"
author: "Edimer David Jaramillo"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: cerulean
    highlight: pygments
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Datos encuesta

```{r}
library(tidyverse)
library(readxl)
datos <- read_excel("encuesta_bien_excel.xlsx")
datos
```

# Analizando la normalidad

- Gráficos:
  - Histogramas o densidades
  - Cuantil-Cuantil (Q-Q Norm)
- Contraste de hipótesis:
  - Prueba de Shapiro Wilk
  - Prueba de Anderson Darling
  
## Densidades

```{r}
datos %>% 
  ggplot(mapping = aes(x = promedio_academico)) +
  geom_density()
```

## Q-Q Norm

- Con el paquete ggplot2:

```{r}
datos %>% 
  ggplot(mapping = aes(sample = promedio_academico)) +
  geom_qq() +
  geom_qq_line()
```

- Con el paquete ggpubr:

```{r}
library(ggpubr)
ggqqplot(data = datos$promedio_academico)
```

- Con el paquete car:

```{r}
library(car)
qqPlot(x = datos$promedio_academico)
```

